### ISSUE TITLE
Error while compiling source code on dev

### ISSUE THREAD

**Issue by stdevMauricio** [skycoin/net#19]
I'm currently working on #17 and when I try to compile I get the following error.
```
# github.com/skycoin/net/skycoin-messenger/op
skycoin-messenger/op/login.go:39:9: cannot assign 1 values to 2 variables
```
Using golang 1.9

**Comment by vyloy** [comment]
Fixed.
Please try again.

**Comment by stdevMauricio** [comment]
I still can't compile. Can you point me to the fix?

**Comment by vyloy** [comment]
6e656ef

**Comment by vyloy** [comment]
Please update to the latest commit.
